resources:
- name: common-scripts
  type: git
  source:
    uri: git@github.com:dansmithy/concourse-experiment.git
    branch: master
    disable_ci_skip: true
    private_key: {{ssh_private_key}}
- name: js-source
  type: git
  source:
    uri: git@gist.github.com:abeca9aac16c3d705ff7539d13a12b47.git
    branch: master
    disable_ci_skip: true
    private_key: {{ssh_private_key}}
- name: documentation-source
  type: git
  source:
    uri: git@gist.github.com:85007ebbccfd2a43d3af2f8a738aaf70.git
    branch: master
    disable_ci_skip: true
    private_key: {{ssh_private_key}}
- name: api-source
  type: git
  source:
    uri: git@gist.github.com:9a64e847eacd4e1eb874abefe5d97d4e.git
    branch: master
    disable_ci_skip: true
    private_key: {{ssh_private_key}}
- name: config-dev-source
  type: git
  source:
    uri: git@gist.github.com:20c8f0e138972b7df5c91f7fbd39e768.git
    branch: master
    disable_ci_skip: true
    private_key: {{ssh_private_key}}
- name: js-binary
  type: s3
  source:
    bucket: djs-concourse
    region_name: eu-west-1
    versioned_file: js-build.txt
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
- name: documentation-binary
  type: s3
  source:
    bucket: djs-concourse
    region_name: eu-west-1
    versioned_file: documentation-build.txt
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
- name: web-binary
  type: s3
  source:
    bucket: djs-concourse
    region_name: eu-west-1
    versioned_file: web-build.txt
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
- name: api-binary
  type: s3
  source:
    bucket: djs-concourse
    region_name: eu-west-1
    versioned_file: api-build.txt
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}


jobs:
- name: js-build
  plan:
  - get: js-source
  - get: common-scripts
  - task: job_work
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: js-source
        path: input
      - name: common-scripts
      outputs:
      - name: output
      run:
        path: common-scripts/scripts/build-source.sh
        args: ['foo-source']
  - put: js-binary
    params:
      file: output/binary
      acl: public-read
- name: documentation-build
  plan:
  - get: documentation-source
  - get: common-scripts
  - task: job_work
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: documentation-source
        path: input
      - name: common-scripts
      outputs:
      - name: documentation-output
      run:
        path: common-scripts/scripts/build-source.sh
        args: ['bar-source']
  - put: documentation-binary
    params:
      file: output/binary
      acl: public-read
- name: web-build
  plan:
  - get: js-binary
    passed: [js-build]
    trigger: true
  - get: documentation-binary
    passed: [documentation-build]
    trigger: true
  - get: common-scripts
  - task: job_work
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: js-binary
        path: input1
      - name: documentation-binary
        path: input2
      - name: common-scripts
      outputs:
      - name: output
      run:
        path: common-scripts/scripts/build-combine.sh
        args: ['js-build.txt', 'documentation-build.txt']
  - put: web-binary
    params:
      file: output/binary
      acl: public-read
- name: web-dev-deploy
  plan:
  - get: web-binary
    passed: [web-build]
    trigger: true
  - task: job_work
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: echo
        args: ['Deploying web to dev']
- name: web-test
  plan:
  - get: web-binary
    passed: [web-dev-deploy]
    trigger: true
  - get: api-binary
    passed: [api-dev-deploy]
    trigger: true
  - task: job_work
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: echo
        args: ['Doing test of web']
- name: web-prod-deploy
  plan:
  - get: web-binary
    passed: [web-test]
    trigger: true
  - task: job_work
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: echo
        args: ['Deploying web to prod']
- name: api-build
  plan:
  - get: api-source
  - get: common-scripts
  - task: job_work
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: api-source
        path: input
      - name: common-scripts
      outputs:
      - name: output
      run:
        path: common-scripts/scripts/build-source.sh
  - put: api-binary
    params:
      file: output/binary
      acl: public-read
- name: api-dev-deploy
  plan:
  - get: api-binary
    passed: [api-build]
    trigger: true
  - get: config-dev-source
    trigger: true
  - task: job_work
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: echo
        args: ['Deploying to dev']
- name: api-test
  plan:
  - get: api-binary
    passed: [api-dev-deploy]
    trigger: true
  - task: job_work
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: sleep
        args: [20]
- name: api-prod-deploy
  plan:
  - get: api-binary
    passed: [api-test, web-test]
    trigger: true
  - task: job_work
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: echo
        args: ['Deploying api']
