resources:
- name: common-scripts
  type: git
  source:
    uri: git@github.com:dansmithy/concourse-experiment.git
    branch: master
    disable_ci_skip: true
    private_key: {{ssh_private_key}}
- name: foo-source
  type: git
  source:
    uri: git@gist.github.com:abeca9aac16c3d705ff7539d13a12b47.git
    branch: master
    disable_ci_skip: true
    private_key: {{ssh_private_key}}
- name: foo-binary
  type: s3
  source:
    bucket: djs-concourse
    region_name: eu-west-1
    versioned_file: foo-build.txt
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}  

jobs:
- name: foo-build
  plan:
  - get: foo-source
  - get: common-scripts
  - task: build-foo
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: foo-source
      - name: common-scripts
      outputs:
      - name: foo-output
      run:
        path: common-scripts/scripts/build-foo.sh
  - put: foo-binary
    params:
      file: foo-output/foo-source
      acl: public-read