resources:
- name: version
  type: semver
  source:
    bucket: djs-concourse
    region_name: eu-west-1
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    initial_version: 1.0.0
jobs:
- name: navi
  plan:
  - get: version
    params: {bump: minor}
  - put: version
    params: {file: version/number}
  - task: say-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: printenv
